name: zebra_datawedge
description: Support hardware scanner for Zebra devices (ET5X) to receive intent and parse it into readable data.
version: 0.1.3
homepage: https://github.com/javaherisaber/flutter-zebra-datawedge

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: io.mway.zebra_datawedge
        pluginClass: ZebraDatawedgePlugin

